/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    documents: Document;
    'change-requests': ChangeRequest;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'change-requests': ChangeRequestsSelect<false> | ChangeRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    speisekarte: Speisekarte;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    speisekarte: SpeisekarteSelect<false> | SpeisekarteSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Foto oder PDF hochladen (z.B. die neue Speisekarte). Wenn dabei etwas auf der Website geändert werden soll, einfach unten beschreiben — es wird beim Speichern automatisch angewendet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  /**
   * In eigenen Worten, z.B. „Übernimm die neuen Öffnungszeiten von dieser Karte“. Die Datei wird mitgelesen und die Änderung beim Speichern direkt angewendet. Leer lassen, wenn die Datei nur abgelegt werden soll.
   */
  prompt?: string | null;
  /**
   * Was auf der Website geändert wurde — oder warum es nicht ging.
   */
  ergebnis?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Beschreibt die gewünschte Änderung (z.B. „Übernimm die Preise aus der angehängten Karte“), hängt bis zu 5 Fotos/PDFs an und speichert — die Website wird direkt aktualisiert.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-requests".
 */
export interface ChangeRequest {
  id: number;
  /**
   * In eigenen Worten: Was soll sich auf der Website ändern? Die angehängten Dateien werden mitgelesen.
   */
  prompt: string;
  attachments?: (number | Document)[] | null;
  status?: ('offen' | 'angewendet' | 'fehlgeschlagen') | null;
  /**
   * Was die KI geändert hat — oder warum es nicht ging.
   */
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'change-requests';
        value: number | ChangeRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  prompt?: T;
  ergebnis?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "change-requests_select".
 */
export interface ChangeRequestsSelect<T extends boolean = true> {
  prompt?: T;
  attachments?: T;
  status?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    image: number | Media;
    reserveLabel: string;
    /**
     * Die mittlere Zeile wird automatisch mit der Adresse aus den Einstellungen verlinkt.
     */
    columns?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  gallery: {
    eyebrow: string;
    heading: string;
    text: string;
    /**
     * Die Collage-Anordnung ist Teil des Designs und richtet sich nach der Reihenfolge — das erste Bild ist das große oben. Bildunterschrift ist optional.
     */
    images?:
      | {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  story: {
    eyebrow: string;
    heading: string;
    chapters?:
      | {
          kicker: string;
          heading: string;
          paragraphs?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    quote: {
      text: string;
      author: string;
    };
    ctaLabel: string;
  };
  /**
   * Die Gerichte selbst stehen im globalen Dokument „Speisekarte“.
   */
  menu: {
    eyebrow: string;
    heading: string;
    ctaLabel: string;
  };
  specials: {
    eyebrow: string;
    heading: string;
    items?:
      | {
          cadence: string;
          title: string;
          description: string;
          price: string;
          unit?: string | null;
          id?: string | null;
        }[]
      | null;
    barEyebrow: string;
    bar?:
      | {
          name: string;
          price: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    footnote?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  contact: {
    heading: string;
    reserveEyebrow: string;
    reserveLinkLabel: string;
    /**
     * Die Adresse steht automatisch dazwischen — hier stehen nur die Zusätze.
     */
    infoItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    hoursHeading: string;
    mapCtaLabel: string;
  };
  /**
   * Die eigene Seite unter /reservierung.
   */
  reservation: {
    eyebrow: string;
    heading: string;
    text: string;
    reserveEyebrow: string;
    image: number | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Die Karte, die auf der Startseite aufgeklappt wird. Kategorien und Gerichte lassen sich per Drag & Drop umsortieren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speisekarte".
 */
export interface Speisekarte {
  id: number;
  sections?:
    | {
        title: string;
        en: string;
        note?: string | null;
        items?:
          | {
              name: string;
              description?: string | null;
              /**
               * Leer lassen, wenn stattdessen Portionsgrößen angegeben sind.
               */
              price?: string | null;
              sizes?:
                | {
                    label: string;
                    price: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footnote: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Schaltet den Chat-Assistenten unten rechts auf der Website ein oder aus. Die Änderung greift innerhalb von etwa einer Minute.
   */
  phillipEnabled?: boolean | null;
  meta: {
    title: string;
    description: string;
    siteUrl: string;
  };
  contact: {
    name: string;
    subtitle: string;
    since: string;
    street: string;
    city: string;
    cityNote?: string | null;
    phoneDisplay: string;
    phoneNumber: string;
    phoneNote: string;
    email: string;
    legalName: string;
    mapsEmbedSrc: string;
    mapsLink: string;
    fullMenuUrl: string;
  };
  /**
   * Ein Eintrag pro Wochentag, beginnend mit Montag. „Von“ und „Bis“ leer lassen = Ruhetag. Sie steuern nur die Anzeige „Jetzt geöffnet“ — angezeigt wird immer der Text unter „Zeiten“.
   */
  hours?:
    | {
        day: string;
        time: string;
        openFrom?: string | null;
        openUntil?: string | null;
        id?: string | null;
      }[]
    | null;
  hoursSummary?:
    | {
        days: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  kitchenNote: string;
  /**
   * Wird endlos wiederholt, getrennt durch das goldene Rauten-Zeichen.
   */
  marquee?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  marqueeSrLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        image?: T;
        reserveLabel?: T;
        columns?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        images?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        chapters?:
          | T
          | {
              kicker?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              author?: T;
            };
        ctaLabel?: T;
      };
  menu?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        ctaLabel?: T;
      };
  specials?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              cadence?: T;
              title?: T;
              description?: T;
              price?: T;
              unit?: T;
              id?: T;
            };
        barEyebrow?: T;
        bar?:
          | T
          | {
              name?: T;
              price?: T;
              description?: T;
              id?: T;
            };
        footnote?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        heading?: T;
        reserveEyebrow?: T;
        reserveLinkLabel?: T;
        infoItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        hoursHeading?: T;
        mapCtaLabel?: T;
      };
  reservation?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        reserveEyebrow?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speisekarte_select".
 */
export interface SpeisekarteSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        en?: T;
        note?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              price?: T;
              sizes?:
                | T
                | {
                    label?: T;
                    price?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  footnote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phillipEnabled?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        siteUrl?: T;
      };
  contact?:
    | T
    | {
        name?: T;
        subtitle?: T;
        since?: T;
        street?: T;
        city?: T;
        cityNote?: T;
        phoneDisplay?: T;
        phoneNumber?: T;
        phoneNote?: T;
        email?: T;
        legalName?: T;
        mapsEmbedSrc?: T;
        mapsLink?: T;
        fullMenuUrl?: T;
      };
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        openFrom?: T;
        openUntil?: T;
        id?: T;
      };
  hoursSummary?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  kitchenNote?: T;
  marquee?:
    | T
    | {
        text?: T;
        id?: T;
      };
  marqueeSrLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}